# Email Notification Jobs
daily_digest:
  class: NotificationSchedulerJob
  queue: default
  args: ["daily_digest"]
  schedule: at 8am every day

overdue_reminders:
  class: NotificationSchedulerJob
  queue: default
  args: ["overdue_reminders"]
  schedule: at 10am every day

due_today_reminders:
  class: NotificationSchedulerJob
  queue: default
  args: ["due_today_reminders"]
  schedule: at 9am every day

weekly_summary:
  class: NotificationSchedulerJob
  queue: default
  args: ["weekly_summary"]
  schedule: at 8am every sunday

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
